# Generated by Django 5.1.6 on 2025-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('Challan_number', models.CharField(max_length=50)),
                ('Challan_number_date', models.DateField()),
                ('order_number', models.CharField(max_length=50)),
                ('consignee_name', models.CharField(max_length=255)),
                ('consignee_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('consignee_state_code', models.CharField(max_length=10)),
                ('transport_mode', models.CharField(blank=True, choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('ship', 'Ship'), ('other', 'Other')], max_length=50, null=True)),
                ('due_date', models.DateField()),
                ('payment_terms', models.CharField(max_length=50)),
                ('place_supply', models.CharField(max_length=150)),
                ('lr_number', models.CharField(max_length=50)),
                ('lr_date', models.DateField()),
                ('lr_time', models.TimeField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_supply', models.DateField(blank=True, null=True)),
                ('time_supply', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bill_invoice_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bill_invoice_invoiceitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, default='Unknown Vendor', max_length=250, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'bill_invoice_vendor',
                'managed': False,
            },
        ),
    ]
