# Generated by Django 5.1.6 on 2025-04-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0003_billinvoice_delete_supplier_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='p_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, default='000000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, default='Unknown Vendor', max_length=250, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='vendor',
            table=None,
        ),
    ]
