# Generated by Django 5.1.6 on 2025-04-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0004_vendor_p_no_vendor_pan_vendor_vendor_code_and_more'),
        ('item', '0002_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinvoice',
            name='description_name',
        ),
        migrations.AddField(
            model_name='billinvoice',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_invoice_stock', to='item.stock'),
        ),
        migrations.AlterField(
            model_name='billinvoice',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_invoice_vendor', to='bill_invoice.vendor'),
        ),
    ]
