# Generated by Django 5.1.6 on 2025-04-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0005_remove_billinvoice_description_name_and_more'),
        ('item', '0003_rename_name_stock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('supplier', models.CharField(max_length=500)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.stock')),
            ],
        ),
    ]
