# Generated by Django 5.1.6 on 2025-04-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0006_billinvoiceitem'),
        ('item', '0003_rename_name_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinvoiceitem',
            name='bill_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill_invoice.billinvoice'),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.stock'),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
