# Generated by Django 5.1.6 on 2025-04-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0007_billinvoiceitem_bill_invoice_and_more'),
        ('item', '0003_rename_name_stock_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='bill_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bill_invoice.billinvoice'),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.stock'),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinvoiceitem',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
