# Generated by Django 5.1.6 on 2025-04-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_invoice', '0008_alter_billinvoiceitem_bill_invoice_and_more'),
        ('item', '0003_rename_name_stock_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='ItemStock',
        ),
    ]
