# Generated by Django 5.1.6 on 2025-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_stock_itemstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstock',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='stock_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
