# Generated by Django 5.1.6 on 2025-04-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_itemstock_hsn_code_alter_itemstock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstock',
            options={'managed': False},
        ),
    ]
