# Generated by Django 5.1.6 on 2025-04-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_itemstock_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemstock',
            table='itemstock',
        ),
        migrations.CreateModel(
            name='DefectiveStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defective_quantity', models.IntegerField()),
                ('reusable_quantity', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='item.itemstock')),
            ],
        ),
    ]
