# Generated by Django 5.1.6 on 2025-04-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_itemstock_table_defectivestock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectivestock',
            options={'managed': False},
        ),
    ]
